import { INodeProperties } from 'n8n-workflow';

export const employeeCreateDescription: INodeProperties[] = [
  {
    displayName: 'Name',
    name: 'name',
    type: 'string',
    default: '',
    required: true,
    description: "Employee's full name",
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Email',
    name: 'email',
    type: 'string',
    default: '',
    placeholder: 'name@example.com',
    description: 'Email address',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Mobile',
    name: 'mobile',
    type: 'string',
    default: '',
    description: 'Mobile phone number',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Gender',
    name: 'gender',
    type: 'options',
    options: [
      { name: 'Male', value: 'male' },
      { name: 'Female', value: 'female' },
    ],
    default: 'male',
    description: 'Gender',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Status',
    name: 'status',
    type: 'options',
    options: [
      { name: 'Active', value: 'active' },
      { name: 'Inactive', value: 'inactive' },
    ],
    default: 'active',
    description: 'Employment status',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Login',
    name: 'login',
    type: 'options',
    options: [
      { name: 'Enable', value: 'enable' },
      { name: 'Disable', value: 'disable' },
    ],
    default: 'enable',
    description: 'Login access',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Locale',
    name: 'locale',
    type: 'string',
    default: 'en',
    description: 'Locale code',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Employee Code',
    name: 'employeeCode',
    type: 'string',
    default: '',
    description: 'Employee ID / code',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Address',
    name: 'address',
    type: 'string',
    default: '',
    description: 'Address',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Joining Date',
    name: 'joiningDate',
    type: 'string',
    default: '',
    description: 'YYYY-MM-DD',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Department ID',
    name: 'department',
    type: 'number',
    default: 0,
    description: 'Department numeric ID',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Designation ID',
    name: 'designation',
    type: 'number',
    default: 0,
    description: 'Designation numeric ID',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Preferred Name',
    name: 'preferredName',
    type: 'string',
    default: '',
    description: 'Preferred name',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Username',
    name: 'username',
    type: 'string',
    default: '',
    required: true,
    description: 'Username for login',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
  {
    displayName: 'Timezone',
    name: 'timezone',
    type: 'string',
    default: 'Asia/Jakarta',
    description: 'Timezone (IANA)',
    displayOptions: { show: { operation: ['employee:create'] } },
  },
];
